Supplemented the #includes with a std::string definition.
The compiler no longer complains about this file.

The error yielded was:
In file included from ltdraw.cc:13:0:
ltdraw.h:35:12: error: ‘string’ has not been declared
ltdraw.h:38:20: error: ‘string’ does not name a type
ltdraw.h:38:28: warning: ISO C++ forbids declaration of ‘format’ with no type [-fpermissive]
ltdraw.h:55:8: error: ‘string’ does not name a type