Supplemented the #includes with a std::string definition.
The compiler no longer complains about this file.

The error yielded was:
In file included from lbdraw.cc:13:0:
lbdraw.h:52:8: error: ‘string’ does not name a type